CREATE DATABASE IF NOT EXISTS g7tech_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE g7tech_db;

CREATE TABLE IF NOT EXISTS portfolio_profile (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) DEFAULT '',
  address VARCHAR(255) DEFAULT '',
  about_me TEXT DEFAULT NULL,
  profile_picture VARCHAR(255) DEFAULT '',
  skills JSON DEFAULT NULL,
  social_links JSON DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS portfolio_projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  url VARCHAR(255) DEFAULT '#',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
